"""
Django settings for libro_prestamos project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializar django-environ y leer archivo .env si existe
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-fallback-key-for-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto True en desarrollo, False en producción
DEBUG = env('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'core.email_backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.core.mail': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "anymail",  # Backend de email para APIs (Mailgun, SendGrid, etc.)
    "core",
    "usuarios",
    "libros",
    "prestamos",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.SessionInvalidationMiddleware",  # Invalidar sesiones basado en timestamp
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "libro_prestamos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "libro_prestamos.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es-ar"

TIME_ZONE = "America/Argentina/Buenos_Aires"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
# En desarrollo, Django busca archivos estáticos en estas ubicaciones
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# En producción, STATIC_ROOT es donde se recopilan todos los archivos estáticos
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Email Configuration
# Leer variables de entorno, con valores por defecto para desarrollo
# Por defecto, en desarrollo se usa consola (los emails se muestran en la terminal)
# En desarrollo, SIEMPRE usar el backend de consola UTF-8 para evitar problemas de codificación
# IMPORTANTE: En desarrollo, forzar uso de consola incluso si EMAIL_BACKEND está en .env
# IMPORTANTE: En producción (especialmente PythonAnywhere), usar API HTTP de Mailgun en lugar de SMTP
# porque PythonAnywhere bloquea conexiones SMTP salientes en planes gratuitos
if DEBUG:
    # Forzar backend de consola UTF-8 en desarrollo
    EMAIL_BACKEND = 'core.email_backends.UTF8ConsoleEmailBackend'
    # Limpiar para asegurar que no se use SMTP en desarrollo
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    EMAIL_HOST = 'smtp.gmail.com'  # Solo para referencia, no se usa en desarrollo
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    # En producción, usar la API HTTP de Mailgun (no SMTP)
    # Esto es necesario para PythonAnywhere que bloquea SMTP saliente en planes gratuitos
    # django-anymail permite usar la API HTTP de Mailgun
    EMAIL_BACKEND = env('EMAIL_BACKEND', default='anymail.backends.mailgun.EmailBackend')
    
    # Configuración de Mailgun vía API (no SMTP)
    ANYMAIL = {
        "MAILGUN_API_KEY": env('MAILGUN_API_KEY', default=''),
        "MAILGUN_SENDER_DOMAIN": env('MAILGUN_SENDER_DOMAIN', default=''),  # ej: mg.bibliotecacolectiva.com o sandboxXXXXX.mailgun.org
        "MAILGUN_API_URL": env('MAILGUN_API_URL', default='https://api.mailgun.net/v3'),
    }
    
    # Para compatibilidad con código que pueda usar variables SMTP antiguas
    # (no se usan con API, pero las mantenemos por si acaso)
    EMAIL_HOST = env('EMAIL_HOST', default='smtp.mailgun.org')
    EMAIL_PORT = env.int('EMAIL_PORT', default=587)
    EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
    EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

# Configuración común
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@bibliotecacolectiva.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
