# Generated by Django 5.1.4 on 2024-12-10 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_prestamo_devuelto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prestamo",
            name="prestador",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prestamos_realizados",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
