# Generated by Django 6.0.1 on 2026-01-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='session_invalidated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp para invalidar todas las sesiones anteriores', null=True),
        ),
    ]
