# Generated by Django 6.0.1 on 2026-01-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_email_change_token'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailchangetoken',
            name='core_emailc_token_66abff_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailchangetoken',
            name='core_emailc_user_id_41034c_idx',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='libro',
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='core_passwo_token_95f98a_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='core_passwo_user_id_2397bf_idx',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='prestatario',
        ),
        migrations.RemoveField(
            model_name='emailchangetoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.DeleteModel(
            name='EmailChangeToken',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
