# Generated by Django 6.0.1 on 2026-01-17 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('comentario_devolucion', models.TextField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_realizados', to=settings.AUTH_USER_MODEL)),
                ('prestatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
